# 数据库类别
type=opengauss
# 连接 URL，当前驱动实际接受 jdbc:postgresql://<host>:<port>/<database>
# url=jdbc:opengauss://localhost:15432/tpcc_100
url=jdbc:opengauss://192.168.199.209:5434/postgres
# 连接用户
# user=benchmarksql
user=test1230
# 连接密码
# password=BenchmarkSql@123
password=Test1234