# 数据库类别
type=opengauss
# 连接 URL，格式为 jdbc:opengauss://<host>:<port>/<database>
url=jdbc:opengauss://192.168.199.249:15432/tpcc_2
# 连接用户
user=benchmarksql
# 连接密码
password=BenchmarkSql@123

# url=jdbc:opengauss://192.168.199.209:5434/postgres
# user=test1230
# password=Test1234